version: '2'
services:
  app:
    build: .
    container_name: aggregatorapp
    ports:
      - "9000:9000" # ws broadcasting port for stream on unique txs
  db:
    image: "redis:latest"
    container_name: aggregatordb

